categorical_groups: {}
cell_type: LSTM
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id___auto_group_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAAAAAAAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - _auto_group_id
  lags: null
  max_encoder_length: 30
  max_prediction_length: 253
  min_encoder_length: 30
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 253
  predict_mode: false
  randomize_length: null
  scalers: {}
  static_categoricals: null
  static_reals: null
  target: _target_column
  target_normalizer: &id002 !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDQAAADIxODgxNTExMjI5MjhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMTg4
        MTUxMTIyOTI4cQFhLgEAAAAAAAAAniWhRw==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    max_length: null
    method: standard
    method_kwargs: {}
    scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDQAAADIxODgxNTExMjc0MDhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMTg4
        MTUxMTI3NDA4cQFhLgEAAAAAAAAAfYTqRQ==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    transformation: relu
  time_idx: _auto_time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals: []
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - _target_column
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_size: 10
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: -1
monotone_constraints: {}
n_plotting_samples: null
n_validation_samples: null
optimizer: adam
optimizer_params: null
output_transformer: *id002
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
rnn_layers: 2
static_categoricals: []
static_reals: []
target: _target_column
target_lags: {}
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder:
- _target_column
weight_decay: 0.0
x_categoricals: []
x_reals:
- _target_column
